### ISSUE TITLE
Add /load command

### ISSUE THREAD

**Issue by schultbr** [fortenbt/slack-msgbot#8]
Ideal usage: msgbot /load [json string]

json string ideally comes from msgbot /dumpcfg or some such command that i've yet to implement. If it fails to parse, new config wont be applied.

Goal here is to be able to allow a user to rapidly change between pre-configured configurations.

**Comment by schultbr** [comment]
Also I have no idea how @fortenbt classified his issue as an enhancement, but that should be the case here too.

**Comment by fortenbt** [comment]
![image](https://cloud.githubusercontent.com/assets/1106428/16532170/371a9e7c-3f9e-11e6-94d6-87de97655305.png)

**Comment by schultbr** [comment]
Figures. Thanks, admin man.

![capture](https://cloud.githubusercontent.com/assets/1130205/16532436/eff00562-3f9f-11e6-8a87-42c19d25dc44.PNG)

**Comment by schultbr** [comment]
This is in as of PR #14
