### ISSUE TITLE
Add /gif functionality

### ISSUE THREAD

**Issue by fortenbt** [fortenbt/slack-msgbot#9]
Probably have it set image_url field of attachment.

Attachment image should be retrieved by posting what slack would normally post to rightgif

**Comment by schultbr** [comment]
so is the thought that slack won't try and retrieve the URL directly but will actually post a command to the bot?

**Comment by fortenbt** [comment]
msgbot should check for /gif. It will then post the /gif message to RightGIF and get the response.

**Comment by schultbr** [comment]
~~I haven't seen anything that led me down the path of even expecting them to do anything with _url tags but fetch them directly as formatted, hence the question.~~

haha exactly where i was going to go. test that and see if rightgif responds. i've had some issues with it but that was via slackbot and not a bot using my auth token

**Comment by schultbr** [comment]
Where is this functionality? is it pretty much fully implemented except for the weird "timeout" computer says no bug? Oh, and the  deletion of the rightgif message

**Comment by fortenbt** [comment]
Yeah. I should create those issues for this feature branch.

**Comment by fortenbt** [comment]
As the main functionality of this is complete, I am closing this. Any usability and feature updates for this should be put on new issues.
